### ISSUE TITLE
Problem using Nested Completion

### ISSUE THREAD

**Issue by gl4ssesbo1** [prompt-toolkit/python-prompt-toolkit#1227]
Hello!

I'm trying to integrate the nested_autocompletion example into my code and I'm having a problem.
My code is a console based app that will run some modules. Modules are inside directories and they will be called using the format:
                                    **dir/module name**

```
My code is this:

from promt_toolkit import prompt
from promt_toolkit.completions import NestedCompleter
from promt_toolkit.shortcuts import CompleteStyle

completer = NestedCompleter.from_nested_dict(
    {
         "show":{
               "mod1/hello":None,
               "mod1/hello2":None
             }
    }
)
```

text = prompt(">>> ", completer=completer, complete_style=CompleteStyle.READLINE_LIKE)

But when I enter show mod1 and press tab, it only fills until:
                           **show mod1/**

And does not even suggest the other parts of the command.
What am I doing wrong?

Thank you!

**Comment by premyslc** [comment]
I think, that it is because it doesn't find whole last word  (aka document.text_before_cursor, see in code). It using regexp expression (document._FIND_WORD_RE) to find last word before cursor,  but it doesn't contains slash or such character. You can change regexp for WordCompleter, but not for NestedCompleter. May be you may use WordCompleter instead of nested dict and change search pattern. 

Something like:
"show": WordCompleter(words=("mod1/hello", "mod1/hello2"), pattern=....)...

**Comment by premyslc** [comment]
I think, that it is because it doesn't find whole last word (aka
document.text_before_cursor, see in code). It using regexp expression
(document._FIND_WORD_RE) to find last word before cursor, but it doesn't
contains slash or such character. You can change regexp for
WordCompleter, but not for NestedCompleter. May be you may use
WordCompleter instead of nested dict and change search pattern.

Something like:
```
"show": WordCompleter(words=("mod1/hello", "mod1/hello2"),
pattern=re.compile(r"([a-zA-Z0-9_\\/]+|[^a-zA-Z0-9_\s]+)"))...
```

**Comment by gl4ssesbo1** [comment]
This one solved it. Thank you very much. Will be closing the issue with this.
