### ISSUE TITLE
deprecation warning with Python 3.10

### ISSUE THREAD

**Issue by jnoortheen** [prompt-toolkit/python-prompt-toolkit#1440]
Python 3.10 is still beta. This is just a heads up.  Here is the full warning

```
xsh-rVZlQJi1-py3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py:878: DeprecationWarning: There is no current event loop
  loop = get_event_loop()
```

**Comment by jonathanslenders** [comment]
Thanks for bringing this to my attention!

Given that we are still supporting Python 3.6, I think we need a wrapper (in ``prompt_toolkit/eventloop/utils.py``) that uses ``get_running_loop`` if available and otherwise ``get_event_loop``. Is this something you're interested in contributing?

There are various places where it's used:
```python
./shortcuts/prompt.py
./shortcuts/dialogs.py
./shortcuts/progress_bar/base.py
./shortcuts/utils.py
./input/vt100.py
./input/win32.py
./history.py
./application/application.py
./contrib/telnet/server.py
./contrib/ssh/server.py
./eventloop/inputhook.py
./eventloop/async_generator.py
./eventloop/utils.py
```

**Comment by jnoortheen** [comment]
@jonathanslenders yes I am. This means updating the github actions as well right?

**Comment by mattmc3** [comment]
Any updates on this issue? A fresh install of Xonsh will emit this deprecation error on every command since Python 3.10 is now out.

Instead of adding something to `prompt_toolkit/eventloop/utils.py`, would it preferable to do a simple conditional import in the relevant files? I'm willing to attempt a PR:

```python
try:
    from asyncio import get_running_loop
except ImportError:
    from asyncio import get_event_loop as get_running_loop
```

**Comment by mattmc3** [comment]
I opened a PR. See above.

**Comment by henryiii** [comment]
FYI, brew has now switched the xonsh recipe to Python 3.10, so this pops up all the time on any brew installed xonsh. Brew has migrated over 150 formula, and is migrating the other 450, so this will pop up on anything that moves to Python 3.10 and uses prompt-toolkit.

**Comment by mattmc3** [comment]
Vote to close this issue. Can confirm that prompt-toolkit 3.0.22 works great in Xonsh on Python 3.10 with my merged PR. For Xonsh users, you can simply `xpip install prompt-toolkit --upgrade` if you are on an earlier version and still seeing the deprecation warning.
