### ISSUE TITLE
Vi mode interpreting <Esc>h as delete-word

### ISSUE THREAD

**Issue by ianbrody** [prompt-toolkit/python-prompt-toolkit#1573]
I have vi mode enabled, timeoutlen = 0.2 and ttimeoutlen = 0.2. If I set them much shorter, then I can't hit things like f[letter] (in normal mode) in time. But this is long enough that I often hit `<Esc>h` in < 0.2 seconds, which results in the word before the cursor being deleted. Or, I hit `<Esc>u` too fast, which results in the word after the cursor to be turned into all-caps. Presumably these are escape sequences of some sort, though I do not have this problem in my terminal outside of a prompt_toolkit prompt. Is there some way to turn them off? I'm experiencing this in ipython.

As a side note, I never experienced this problem until ipython upgraded to whatever version of prompt_toolkit that changes the cursor shape in insert mode.

**Comment by jonathanslenders** [comment]
Hi @ianbrody,

This is weird. I can't reproduce this immediately. Which terminal application are you using? And which operating system?

I don't see any ANSI (vt100) escape sequence bound to either ``<esc>h`` or ``<esc>u``, nor is there any key binding bound to this. 
What happens if you try to keep ``timeoutlen`` long (like 1sec), while keeping ``ttimeoutlen`` short (0.2 as in your example)?

It would also be helpful, if you could figure out in which prompt_toolkit version this bug was introduced.

**Comment by ianbrody** [comment]
Funny timing-- I just sat down to play with this some more. It turns out that this is actually ipython's fault; removing the escape key bindings (e.g. `("escape", "h"): nc.backward_kill_word,`) in /usr/lib/python3.10/site-packages/IPython/terminal/shortcuts.py made this go away. There is still something else weird with vi mode and timeouts but I will investigate further to figure out where to report it to.
