### ISSUE TITLE
Add ptpython support to Django's shell

### ISSUE THREAD

**Issue by defrex** [prompt-toolkit/python-prompt-toolkit#25]
This is less an issue, and more a helpful tip that may be worth adding to the README. It's really simple to add ptpython support to Django's `manage.py shell` command. Just add [this gist](https://gist.github.com/defrex/f4bedd533f7ff1a2c0a8) as a manage command in any app in your project.

```
from django.core.management.commands.shell import Command as ShellCommand


class Command(ShellCommand):
    shells = ['ptpython', 'ipython', 'bpython']

    def ptpython(self):
        from prompt_toolkit.contrib.repl import embed
        embed(globals(), locals(), vi_mode=False, history_filename=None)
```

**Comment by ChillarAnand** [comment]
In readme, It is worth mentioning  that `django-extensions-1.4.9` or higher is required to use ptpython.

**Comment by nmvega** [comment]
Wow, funny how I just ran into this wonderful functionality.

Being a huge fan of ptpython, I wanted to replace the iPython behavior in "./manage.py shell" with ptpython behavior because that has vim(1) and other functionality that I like.

So to figure out how I might get that to work, I ran "./manage.py shell_plus" for the first time (as opposed to just "./manage.py shell") and, boom,... where I expected to have only iPython functionality, I unexpectedly had that plus all the ptpython functionality, too! I didn't understand how it could even find ptpython at all. So I Googled and found this, which explains everything.

This is an awesome combination. Thank you very much for your work on this. I really appreciate it.
