### ISSUE TITLE
Prompt in full screen application

### ISSUE THREAD

**Issue by tage64** [prompt-toolkit/python-prompt-toolkit#652]
Hi!
I want to create a full screen application. Then I want to ask the user for some input at some point in my code. I want to use the prompt function. It seems to me that I can't do that. I've tried run_in_terminal, but it doesn't worked in this case.
Is it possible to do that?
Tage!

**Comment by jonathanslenders** [comment]
Hi @tagej,

The ``prompt`` function is not meant to run inside the full screen layout, but ``run_coroutine_in_terminal`` can handle that. It will hide the full screen layout; display the prompt; and go back. The reason to use that instead of ``run_in_terminal`` is because there is already an event loop running that you want to use. ``run_in_terminal`` is meant for running blocking functions. Spawning a new event from in there doesn't work.

It should look something like this:

```python
from prompt_toolkit.application import run_coroutine_in_terminal
from prompt_toolkit.shortcuts import prompt

def display_prompt_in_app():
    future = run_coroutine_in_terminal(prompt('>', async_=True))
```
The ``async_`` flag makes that ``prompt()`` returns a Future/coroutine. In the future, these are probably becoming asyncio Futures/coroutines, but keep in mind that right now, this is prompt_toolkit specific.

If you want to display an input field on top of the full screen application, then you can for instance consider using a ``Float/FloatContainer`` containing a ``prompt_toolkit.widgets.Dialog`` containing a ``prompt_toolkit.widgets.TextArea`` for the input field. You can show/hide this using a ``prompt_toolkit.layout.ConditionalContainer``.

**Comment by tagej** [comment]
Hi @jonathanslenders 
It don't work for me. Here's what I've tested:
`from functools import partial

from prompt_toolkit import prompt
from prompt_toolkit.application import run_coroutine_in_terminal, \
        run_in_terminal
from prompt_toolkit.eventloop import run_until_complete
from prompt_toolkit.key_binding import KeyBindings
from prompt_toolkit.keys import Keys


key_bindings = KeyBindings()
@key_bindings.add(Keys.ControlS)
def _(event):
    f = run_coroutine_in_terminal(partial(prompt, '> ', async_=True))
    run_until_complete(f)
    run_in_terminal(partial(print, f2.result()))
print(prompt('> ', key_bindings=key_bindings))
`

It raised an exception when I pressed control S. Try it out yourself.
Is it a bug? Or just bad code?
Tage

**Comment by lwm** [comment]
Ah, I do see that we have https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/widgets/base.py#L87-L88 which can get me moving along for now. Sorry for the noise.

**Comment by lwm** [comment]
Ah, here is an example which shows you how to build up your own widget that you can control the `BufferControl` with: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/full-screen/simple-demos/autocompletion.py. You can start to piece together a prompt and so on.

**Comment by rogerbassons** [comment]
[My solution](https://github.com/rogerbassons/cli-passwordmanager/commit/a9ed71c0db22b369ab1e844c969413fa4f120342) to this is @jonathanslenders TextArea/input field suggestion:
> If you want to display an input field on top of the full screen application, then you can for instance consider using a `Float/FloatContainer` containing a `prompt_toolkit.widgets.Dialog` containing a `prompt_toolkit.widgets.TextArea` for the input field. You can show/hide this using a `prompt_toolkit.layout.ConditionalContainer`. `TextArea` has several attributes like lexer, completer, etc.. similar to the prompt() function.

Layout like this:
````
search_field = SearchToolbar()
input_field = TextArea(height=1, prompt='/', style='class:input-field', multiline=False, wrap_lines=False, search_field=search_field)
input_field.accept_handler = filterTable

root_container = HSplit([
    Window(content=FormattedTextControl(text=getFormattedTable(selected, filteredList), get_cursor_position=GetCursorPosition())),
    ConditionalContainer(content=input_field, filter=isSearching)
])
layout = Layout(container=root_container)
````
Inside filterTable function you can read user input with input_field.text attribute
