### ISSUE TITLE
Keep bottom_toolbar visible between prompts

### ISSUE THREAD

**Issue by Alphapage** [prompt-toolkit/python-prompt-toolkit#752]
Hello,

Here is my sample code:

```
from prompt_toolkit import prompt
from prompt_toolkit.formatted_text import HTML

def bottom_toolbar():
    return HTML('This is a <b><style bg="ansired">Toolbar</style></b>!')



def main():
    print('A test')
    text=prompt('> ', bottom_toolbar=bottom_toolbar)
    print('You said: %s' % text)
    text = prompt('> ', bottom_toolbar=bottom_toolbar)
    print('You said: %s' % text)


if __name__ == '__main__':
    main()
```
I want to keep the bottom_toolbar always visible, but as soon as I `print` something, then the bottom_toolbar disappears.

Is there a `print(text:str,bottom_toolbar)` function available in prompt_toolkit or maybe I can run/show/hide the bottom_toolbar without using `prompt` ?

Thank you in advance for your help.

**Comment by jonathanslenders** [comment]
Hi @Alphapage,

Unfortunately, this is not possible right now, and it's hard to achieve due to the way terminals work. The bottom toolbar requires a running event loop for it to always render on the correct position, even when the window scrolls or is resized.

A workaround is to create a dummy application (with a dummy layout) with only a bottom toolbar, use the patch_stdout functionality of prompt_toolkit, and call the print statements in a background thread. The dummy application should run as long as things are printed in the background.
