### ISSUE TITLE
Style colors don't work with complete_style=CompleteStyle.READLINE_LIKE?

### ISSUE THREAD

**Issue by hacksterous** [prompt-toolkit/python-prompt-toolkit#791]
yield Completion(text, start_position=-(len(matchWord)), style='fg:green') does not seem to be working when I have

prompt (message,
		completer=completer, 
		history=self.history, 
		complete_while_typing=True, 
		auto_suggest=suggestion,
		complete_style=CompleteStyle.READLINE_LIKE,
		complete_in_thread=True
	)

but works with CompleteStyle.COLUMN

**Comment by jonathanslenders** [comment]
Hi @hacksterous,

This was indeed never implemented, and would be nice to have. I don't know whether I'll have time soon, but a pull request is welcome.

It's the ``_display_completions_like_readline`` function in ``prompt_toolkit/key_binding/bindings/completion.py``. Instead of calling ``app.output.write``, use ``renderer.print_formatted_text``.

**Comment by jonathanslenders** [comment]
Hi @hacksterous,

This should fix it: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/511173b37bf0a98db9af2ca40492bba4a60072f9
Can you try again against the latest master commit?

**Comment by jonathanslenders** [comment]
I'm closing this (it is fixed). Feel free to open again if needed.

Further, the ``display`` parameter of ``Completion`` can now also be formatted text. See: https://github.com/prompt-toolkit/python-prompt-toolkit/commit/7c913f2a872cb6fe8006dce4f6eb62717c820053
